INSERT INTO burgers (burger, devoured) VALUES ('Hamburger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Cheeseburger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Double Cheese Hamburger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Chicken Sandwich', false);
INSERT INTO burgers (burger, devoured) VALUES ('Classic Cheese Burger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Regular Hamburger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Bacon Cheeseburger', false);
INSERT INTO burgers (burger) VALUES ('Double Cheese Bacon Hamburger');
INSERT INTO burgers (burger) VALUES ('Grilled Chicken Sandwich');
INSERT INTO burgers (burger) VALUES ('Classic Cheddar Burger');
INSERT INTO burgers (burger, devoured) VALUES ('Double Cheese Bacon Hamburger', false);
INSERT INTO burgers (burger, devoured) VALUES ('Grilled Chicken Sandwich', false);
INSERT INTO burgers (burger, devoured) VALUES ('Classic Cheddar Burger', false);